name = "preconnect-seatstatus"
main = "src/index.ts"
compatibility_date = "2026-02-27"
workers_dev = false
account_id = "af4e734b34a7218b04e72b7d65a377e1"

[[routes]]
pattern = "seatstatus.preconnect.app/*"
zone_name = "preconnect.app"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SeatHub"]

[[migrations]]
tag = "v2"
deleted_classes = ["SeatHub"]

[vars]
REFRESH_TOKEN = ""

[triggers]
crons = ["*/1 * * * *"]
