version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Dhaka"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "pub"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "dart"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "bundler"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "gradle"
    directory: "/android"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "android"
    commit-message:
      prefix: "chore(deps)"
