include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/pages/api_test.dart
  errors:
    invalid_use_of_protected_member: warning

linter:
  rules:
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
