include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - .firebase/**
    - ios/Pods/**
    - web/.well-known/**

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_final_fields
    - unnecessary_lambdas
    - unnecessary_null_checks
    - use_key_in_widget_constructors
