FROM scratch
COPY printer.exe /printer.exe
COPY admin.bat /admin.bat
COPY user.bat /user.bat
COPY uninstall.bat /uninstall.bat
COPY preprintd-admin.bat /preprintd-admin.bat
COPY preprintd-user.bat /preprintd-user.bat
COPY preprintd-uninstall.bat /preprintd-uninstall.bat
COPY preprintd.sh /preprintd.sh
COPY preprintd-uninstall.sh /preprintd-uninstall.sh
