name: preconnect
description: "Your personalised student portal for BRAC University"
publish_to: "none"

version: 1.6.5+202605035

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.7
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.5
  http: ^1.6.0
  webview_flutter_android: ^4.12.0
  webview_flutter: ^4.13.1
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  image_picker: ^1.2.2
  archive: ^4.0.9
  dart_pdf_reader: ^2.2.0
  flutter_alarmkit: ^0.0.10
  barcode_widget: ^2.0.4
  flutter_flip_card: ^0.0.6
  url_launcher: ^6.3.2
  file_selector: ^1.1.0
  share_plus: ^13.1.0
  open_filex: ^4.7.0
  in_app_update: ^4.2.5
  in_app_review: ^2.0.12
  local_auth: ^3.0.1
  chrome_extension: ^0.4.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - web/icons/Icon-512.png
