name = "preconnect-web"
compatibility_date = "2026-06-18"
workers_dev = false
preview_urls = false
keep_bindings = []

routes = [
  { pattern = "web.preconnect.app", custom_domain = true }
]

[assets]
directory = "./build/web"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"
