name = "preconnect-web"
compatibility_date = "2026-06-18"
preview_urls = false

[assets]
directory = "./build/web"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"
