org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=2
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
dev.steenbakker.mobile_scanner.useUnbundled=false
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseG1GC
android.builtInKotlin=false
android.newDsl=false
android.r8.optimizedResourceShrinking=true
android.enableR8.fullMode=true
