org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
android.useAndroidX=true
dev.steenbakker.mobile_scanner.useUnbundled=false
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseG1GC
android.builtInKotlin=false
android.newDsl=false
android.r8.optimizedResourceShrinking=true
android.enableR8.fullMode=true

org.gradle.configureondemand=true
android.enableJetifier=false
