// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9bRJ0UBq9kHCgD9657W1--z3cfxE6_E',
    appId: '1:53508941136:web:c8bcc291d6b619f886f855',
    messagingSenderId: '53508941136',
    projectId: 'preconnect-bracu',
    authDomain: 'preconnect-bracu.firebaseapp.com',
    storageBucket: 'preconnect-bracu.firebasestorage.app',
    measurementId: 'G-MJ066FW9N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ud3OO4dlyO1Ufz9bf7HnE37HUiGwRgU',
    appId: '1:53508941136:android:02312f60ae1ad0ee86f855',
    messagingSenderId: '53508941136',
    projectId: 'preconnect-bracu',
    storageBucket: 'preconnect-bracu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ZCvq5ULyLnCkEto-CPQx2lsZ7Uqkozk',
    appId: '1:53508941136:ios:daf88e3b91c5941386f855',
    messagingSenderId: '53508941136',
    projectId: 'preconnect-bracu',
    storageBucket: 'preconnect-bracu.firebasestorage.app',
    iosBundleId: 'com.sabbirba.preconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ZCvq5ULyLnCkEto-CPQx2lsZ7Uqkozk',
    appId: '1:53508941136:ios:daf88e3b91c5941386f855',
    messagingSenderId: '53508941136',
    projectId: 'preconnect-bracu',
    storageBucket: 'preconnect-bracu.firebasestorage.app',
    iosBundleId: 'com.sabbirba.preconnect',
  );
}
