opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Upload iOS build to TestFlight"
  lane :upload_build_to_testflight do |options|
    key_content = options[:api_key_content] || ENV["APP_STORE_CONNECT_API_KEY"]
    key_content = key_content.gsub("\\n", "\n") if key_content
    key_id = options[:api_key_id] || ENV["APP_STORE_CONNECT_KEY_ID"]
    issuer_id = options[:api_issuer_id] || ENV["APP_STORE_CONNECT_ISSUER_ID"]

    is_base64 = !key_content.include?("PRIVATE KEY")
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content,
      is_key_content_base64: is_base64
    )

    upload_to_testflight(
      ipa: options[:ipa],
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
end
