[package]
name = "preprintd"
description = "Printer swarm-worker daemon implementation for PreConnect."
authors = ["Anindya Shiddhartha <shiddhartha@tuta.io>"]
license = "GPL-3.0-only"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.0"
hmac = "0.13.0"
reqwest = { version = "0.13.4", features = ["blocking", "rustls", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
socket2 = "0.6.5"

[lints.clippy]
unwrap_used = "deny"
unreachable = "deny"
must_use_candidate = "warn"

[lints.rust]
unused_must_use = "deny"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
